version: '3.1'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:
  teamcity-agent:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ./agents/agent-3/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
